config/routes.rb
Rails.application.routes.draw do
 
 root 'pages#home'
 get 'about', to: 'pages#about'
 get 'contact', to: 'pages#contact'

 resources :articles
 
 get 'signup', to: 'users#new' 
 
 resources :users, exept: [:new]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    
    belongs_to :user
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save {self.email = email.downcase}
    validates :username, presence: true, length: {minimum: 3, maximum: 25}, 
                         uniqueness: {case_sensitive: false}  #nie ważne czy wpiszemy wielkimi czy małymi literami
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 50}, 
                      uniqueness: {case_sensitive: false}, 
                      format: {with: VALID_EMAIL_REGEX}  
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
   before_action :find_article, only: [:edit, :update, :show, :destroy]
   
   def index
      @articles = Article.all
   end
    
   def new
       @article = Article.new
   end
   
   def edit
      @article = Article.find(params[:id])
   end
   
   def create
      @article = Article.new(article_params)
      @article.user = User.first
   if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
   else
      render 'new'
   end
   end

   def update
      @article = Article.find(params[:id])
   if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
   else
      render 'edit'
   end
   end

   def show
      #@article = Article.find(params[:id])
   end
   
   def destroy
      #@article = Article.find(params[:id])
      @article.destroy
      flash[:danger] = "Article was successfully deleted"
      redirect_to articles_path
   end

private

   def find_article
      @article = Article.find(params[:id])
   end
   
   def article_params
      params.require(:article).permit(:title, :description)
   end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
       
   end
   
   def about
       
   end
   
   def contact
      
   end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
   def index
      @users = User.all
   end
   
   def new
       @user = User.new
   end
   
   def create
      @user = User.new(user_params)
      if @user.save
          flash[:success] = "Welcome #{@user.username} to the Alpha Blog!"
          redirect_to articles_path
      else
          render 'new'
      end
   end
   
   def edit
      @user = User.find(params[:id]) 
   end
   
   def update
      @user = User.find(params[:id])
      if @user.update(user_params)
          flash[:success] = "Your account was updated"
          redirect_to articles_path
      else
         redirect 'edit' 
      end
   end
   
   def show
      @user = User.find(params[:id])
   end
    
    private
    
    def user_params
       params.require(:user).permit(:username, :email, :password) 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle") 
    end
    
end

app/views/articles/_article.html.erb
<% obj.each do |art| %>
  <div class='row'>
    <div class='col-xs-8 col-xs-offset-2'>
      <div class='well well-lg'>
        <div class='article-title'>
        <%= link_to art.title, article_path(art) %>
        </div>
        <div class='article-body'>
        <%= truncate(art.description, length: 80) %>
        <div class="article-meta-details">
        <small>Created by: <%= art.user.username if art.user%>, 
                            <%= time_ago_in_words(art.created_at) %> ago,
                Updated:     <%= time_ago_in_words(art.updated_at) %> ago</small>
        </div>        
        </div>
        <div class='article-actions'>
        <%= link_to 'Edit this article', edit_article_path(art), class: 'btn btn-xs btn-primary' %>
        <%= link_to 'Delete this article', article_path(art), method: :delete, data: {confirm: 'Are You sure?' }, class:'btn btn-xs btn-danger' %> 
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@article, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
        <div class='form-group'> 
            <div class='control-label col-sm-2'>
                <%= f.label :title %><br/>
            </div>
                <div class='col-sm-8'>
                    <%= f.text_field :title, class: 'form-control', placeholder: "Title of the Article", autofocus: true %>
                </div>
        </div>

<div class='form-group'> 
    <div class='control-label col-sm-2'>
        <%= f.label :description %>
    </div>
        <div class='col-sm-8'>
            <%= f.text_area :description, rows: 10, class: 'form-control', placeholder: "Description of the Article" %>
        </div>
</div>    

<div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
        <%= f.submit class:'btn btn-primary btn-lg' %>
    </div>
</div>

        <% end %>
<div class='col-xs-4 col-xs-offset-4'>
<p align='center'> [ <%= link_to 'Cancel and back to the articles', articles_path %> ] </p>
</div>
     </div>
</div>

app/views/articles/edit.html.erb
<h1 align='center'> Edit Article - "<%= @article.title %>"  </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align='center'> List of all articles </h1>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align='center'>Title: <%= @article.title %></h2>

<div class='well col-xs-8 col-xs-offset-2'>
  <ul class="listing">
        <div class="row center">
            <div class="col-md-4 col-md-offset-4">
              <li>Created by: </li>
                <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                <li class="article-title">
                    <%= link_to @article.user.username, user_path(@article.user) %>
                </li>
                <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
            </div>
        </div>
    </ul>
  <h4 class='center description'><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class='article-actions'>
  <%= link_to 'Edit this article', edit_article_path(@article), class: 'btn btn-xs btn-primary' %>
  <%= link_to 'Delete this article', article_path(@article), method: :delete, data: {confirm: 'Are You sure?' }, class:'btn btn-xs btn-danger' %> 
  <%= link_to 'View all articles', articles_path, class: 'btn btn-xs btn-success' %>
  <%= link_to 'I want add another article!', new_article_path, class: 'btn btn-xs btn-success' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyright &copy; <a href="https://alpha-blog-damian.herokuapp.com/">Alpha Blog App</a>
            by <a href="https://pl.linkedin.com/in/damian-godlewski">Damian Godlewski</a>
        </small>
        <nav>
            <%= link_to 'About', about_path %> | <%= link_to 'Contact', contact_path %>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class='row'>
  <div class='col=xs-10 col-xs-offset-2'>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href='#' class='close' data-dismiss='alert'>&#215;</a>
        <%= content_tag :div, msg, :id => 'flash_#{name}' if msg.is_a?(String) %>
      </div>  
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add new article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Nothing to do here!</h1>
<%= link_to 'Go back to the most beautifull HOME Page!', root_path %>

<%= link_to image_tag('test.jpg'), 'http://www.facebook.com' %>

app/views/pages/contact.html.erb
<h1>Damian Godlewski</h1>
<ol>
    <li>Phone: </li>
    <li>E-mail: </li>
</ol>

app/views/pages/home.html.erb
<div class="center jumbotron">
<h1>Alpha Blog</h1>
<%= link_to "Sing in now!", "#", class: "btn btn-danger btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class='row'>
        <div class='col-xs-8 col-xs-offset-2'>
            <div class='panel panel-danger'>
                <div class='panel-heading'>
                    <h2 class='panel-title'>
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class='panel-body'>
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                        <li>
                            <%= msg %>
                        </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
    <div class='col-xs-12'>
        <%= form_for(@user, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>
        <div class='form-group'> 
            <div class='control-label col-sm-2'>
                <%= f.label :username %><br/>
            </div>
                <div class='col-sm-8'>
                    <%= f.text_field :username, class: 'form-control', placeholder: "Enter User Name", autofocus: true %>
                </div>
        </div>

<div class='form-group'> 
    <div class='control-label col-sm-2'>
        <%= f.label :email %>
    </div>
        <div class='col-sm-8'>
            <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
        </div>
</div>  

<div class='form-group'> 
    <div class='control-label col-sm-2'>
        <%= f.label :password %>
    </div>
        <div class='col-sm-8'>
            <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
        </div>
</div>    

<div class='form-group'>
    <div class='col-sm-offset-2 col-sm-10'>
        <%= f.submit(@user.new_record? ?  "Sign up" : "Update account", class:'btn btn-primary btn-lg') %>
    </div>
</div>

        <% end %>
<div class='col-xs-4 col-xs-offset-4'>
<p align='center'> [ <%= link_to 'Cancel and back to the articles', articles_path %> ] </p>
</div>
     </div>
</div>

app/views/users/edit.html.erb
<h1 align='center'> Edit your account </h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>

<div align="center">
    <% @users.each do |user| %>
    <ul class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li class="article-title">
                    <%= link_to user.username, user_path(user) %>
                </li>
                <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
            </div>
        </div>
    </ul>
    <% end %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Hi <%= @user.username %>'s</h1>

<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @user, size: 120 %>
    </div>
</div>

<h4 align="center"><%= @user.username %>'s articles</h4>

<%= render 'articles/article', obj: @user.articles %>